---
require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sequel

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: true
  Description: 'Limit lines to 125 characters.'
  Max: 125

Metrics/BlockLength:
  Enabled: true
  IgnoredMethods:
    - before
    - context
    - describe
    - let
    - namespace
    - shared_examples_for

Metrics/MethodLength:
  Enabled: true
  Max: 20

Style/Documentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: true
  Severity: fatal
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
