---
sudo: false
cache: bundler
language: ruby

rvm:
  - 2.5
  - 2.6

# Ensure we don't build for *every* commit (doesn't apply to PR builds)
branches:
  only:
  - master

before_install:
- yes | gem update --system --force
- gem install bundler

script:
- bundle exec rspec --format documentation
